[[headers]]
  for = "/*" # you can configure the correct paths here
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin" # see a list of allowed values here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Cross-Origin-Resource-Policy
